name: gatsby-publish

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
         node-version: 20.18
      - name: Build Gatsby site with legacy OpenSSL support
        run: NODE_OPTIONS=--openssl-legacy-provider yarn run build -- --prefix-paths
      - uses: actions/checkout@v3.5.0
      - uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
